/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jvkubrik;

import java.awt.Image;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author efras
 */
public class jinfKubrik extends javax.swing.JInternalFrame {
    URL urlImagen;
    clsKubrik objKubrik;
    /**
     * Creates new form jinfKubrik
     */
    public jinfKubrik() {
        initComponents();
        objKubrik = new clsKubrik();
        objKubrik.generarPanel(this);
        objKubrik.crearEtiquetas();
        objKubrik.crearBotones(this);
        objKubrik.crearJtxArea();
        objKubrik.llenarMatrizOriginal();
        mostrarImagen(objKubrik.getEtiquetas().get(0), "/imagenes/logometro.jpg");
    }
    public void mostrarImagen(JLabel imagenLogo, String urlImg){
        urlImagen = this.getClass().getResource(urlImg);
        ImageIcon imgL = new ImageIcon(urlImagen);
        Icon imagen = new ImageIcon(imgL.getImage().getScaledInstance(imagenLogo.getWidth(), imagenLogo.getHeight(), Image.SCALE_DEFAULT));
        imagenLogo.setIcon(imagen);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
